name: zero_churn_model
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black=24.8.0
  - flake8=7.1.1
  - isort=5.13.2
  - pip=24.2
  - typer=0.12.5
  - loguru=0.7.2
  - tqdm=4.66.5
  - ipython=8.27.0
  - jupyterlab=4.2.5
  - matplotlib=3.9.2
  - notebook=7.2.2
  - numpy=2.1.1
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - pip:
    - python-dotenv
    - pyarrow==17.0.0
    - mkdocs==1.6.1
    - -e .
