name: zero_churn_model
channels:
  - conda-forge
dependencies:
  - python
  - fastparquet
  - libparquet
  - scipy
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - pip:
    - python-dotenv
    - pyarrow
    - mkdocs
    - -e .
